databases:
  - name: tradelog_db
    databaseName: tradelog_db_ceq2
    user: tralog
    region: singapore

services:
  - type: web
    name: tralog
    env: ruby
    region: singapore
    plan: free
    buildCommand: bundle install && bundle exec rake assets:precompile && bundle exec rails db:migrate
    startCommand: bundle exec rails s -p 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tradelog_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

