default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
 <<: *default
 adapter: mysql2
 encoding: utf8
 pool: 5
 reconnect: false
 database: <%= ENV["MC_DATABASE"] %>
 username: <%= ENV["MC_DB_USERNAME"] %>
 password: <%= ENV["MC_DB_PASSWORD"] %>
 host: <%= ENV["MC_DB_HOSTNAME"] %>

