default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

# production:
#   <<: *default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5

production:
 <<: *default
 adapter: mysql2
 encoding: utf8
 pool: 5
 reconnect: false
 database: 7e7c86a778957d2a0be1d93e87507973
 username: 7e7c86a778957d2a0be1d93e87507973
 password: Sunsunpinpin107
 host: mysql-2.mc.lolipop.lan

